// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P_054_batu_parduotuve.Infrastructure.Database;

#nullable disable

namespace P_054_batu_parduotuve.Infrastructure.Migrations
{
    [DbContext(typeof(ParduotuveContext))]
    partial class ParduotuveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("P_054_batu_parduotuve.Domain.Models.Batas", b =>
                {
                    b.Property<int>("BatasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kaina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BatasId");

                    b.ToTable("Batai");

                    b.HasData(
                        new
                        {
                            BatasId = 1,
                            Kaina = 100m,
                            Pavadinimas = "Kedai",
                            Tipas = "Vyriški"
                        },
                        new
                        {
                            BatasId = 2,
                            Kaina = 200m,
                            Pavadinimas = "Kedai",
                            Tipas = "Moteriški"
                        },
                        new
                        {
                            BatasId = 3,
                            Kaina = 20.21m,
                            Pavadinimas = "Kroksai",
                            Tipas = "Vaikiški"
                        });
                });

            modelBuilder.Entity("P_054_batu_parduotuve.Domain.Models.BatuDydis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("BatuDydisId");

                    b.Property<int>("BatasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dydis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kiekis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BatasId");

                    b.ToTable("BatuDydziai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatasId = 1,
                            Dydis = 42,
                            Kiekis = 10
                        },
                        new
                        {
                            Id = 2,
                            BatasId = 1,
                            Dydis = 43,
                            Kiekis = 11
                        },
                        new
                        {
                            Id = 3,
                            BatasId = 1,
                            Dydis = 44,
                            Kiekis = 12
                        },
                        new
                        {
                            Id = 4,
                            BatasId = 1,
                            Dydis = 45,
                            Kiekis = 13
                        },
                        new
                        {
                            Id = 5,
                            BatasId = 2,
                            Dydis = 36,
                            Kiekis = 10
                        },
                        new
                        {
                            Id = 6,
                            BatasId = 2,
                            Dydis = 37,
                            Kiekis = 11
                        },
                        new
                        {
                            Id = 7,
                            BatasId = 2,
                            Dydis = 38,
                            Kiekis = 12
                        },
                        new
                        {
                            Id = 8,
                            BatasId = 2,
                            Dydis = 39,
                            Kiekis = 13
                        },
                        new
                        {
                            Id = 9,
                            BatasId = 3,
                            Dydis = 30,
                            Kiekis = 10
                        },
                        new
                        {
                            Id = 10,
                            BatasId = 3,
                            Dydis = 31,
                            Kiekis = 11
                        },
                        new
                        {
                            Id = 11,
                            BatasId = 3,
                            Dydis = 32,
                            Kiekis = 12
                        },
                        new
                        {
                            Id = 12,
                            BatasId = 3,
                            Dydis = 33,
                            Kiekis = 13
                        });
                });

            modelBuilder.Entity("P_054_batu_parduotuve.Domain.Models.Pardavimas", b =>
                {
                    b.Property<int>("PardavimasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatuDydisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kiekis")
                        .HasColumnType("INTEGER");

                    b.HasKey("PardavimasId");

                    b.HasIndex("BatuDydisId");

                    b.ToTable("Pardavimai");
                });

            modelBuilder.Entity("P_054_batu_parduotuve.Domain.Models.BatuDydis", b =>
                {
                    b.HasOne("P_054_batu_parduotuve.Domain.Models.Batas", "Batas")
                        .WithMany("Dydziai")
                        .HasForeignKey("BatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batas");
                });

            modelBuilder.Entity("P_054_batu_parduotuve.Domain.Models.Pardavimas", b =>
                {
                    b.HasOne("P_054_batu_parduotuve.Domain.Models.BatuDydis", "BatuDydis")
                        .WithMany()
                        .HasForeignKey("BatuDydisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatuDydis");
                });

            modelBuilder.Entity("P_054_batu_parduotuve.Domain.Models.Batas", b =>
                {
                    b.Navigation("Dydziai");
                });
#pragma warning restore 612, 618
        }
    }
}
